---
version: 2
updates:
  - directory: "/"
    package-ecosystem: github-actions
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
      time: "04:00"
    assignees:
      - "Kampfmoehre"
  - directory: "/"
    groups:
      chai:
        patterns:
          - "chai"
          - "chai-as-promised"
          - "@types/chai"
          - "@types/chai-as-promised"
      commitlint:
        patterns:
          - "@commitlint/*"
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"
          - "@eslint/eslintrc"
          - "@eslint/js"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
          - "typescript-eslint"
    open-pull-requests-limit: 10
    package-ecosystem: npm
    schedule:
      interval: daily
      time: "04:00"
    assignees:
      - "Kampfmoehre"
